config/routes.rb
Rent::Application.routes.draw do
  
  scope '(:locale)' do
    resources :users
    resources :sessions,  :only => [:new, :create, :destroy]
    resources :userposts
  
    resources :users do
      resources :userposts
    end
  
    match '/users/userposts/new', :to => 'userposts#new'
  
    match '/signup',  :to => 'users#new'
    match '/signin',  :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'

    match '/contact', :to => 'pages#contact'
    match '/about',   :to => 'pages#about'
    match '/help',    :to => 'pages#help'

    root :to => 'pages#home'
  end

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %>
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <table class="userposts" summary="User posts">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </td>
  <td class="userpost">
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= wrap(feed_item.content) %></span>
    <span class="timestamp">
      <%= t('.posted') %> <%= time_ago_in_words(feed_item.created_at) %> <%= t('.ago') %>
        <% if current_user?(feed_item.user) %>
          <%= link_to t('.edit'), edit_userpost_path(feed_item) %> |
          <%= link_to t('.delete'), feed_item, :method => :delete,
                                           :confirm => t('.you_sure'),
                                           :title => feed_item.content %>
        <% end %>
    </span>
  </td>
</tr>

app/views/shared/_show_userposts.html.erb
<table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="userpost"><%= t('.all_posts') %></h1>
        <%= render 'shared/feed' %>
      </td>
    </tr>
  </table>

app/views/shared/_signup_now.html.erb
  <h1><%= t('.sample_app') %></h1>

  <p>
    <%= t('.tithome') %>
    <a href="http://railstutorial.org/"><%= t('.rortutorial') %></a>
  </p>

  <%= link_to t('.signup_now'), signup_path, :class => "signup_button round" %>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.name %>|<%= current_user.userposts.count %> <%= t('.post') %>
    </span>
    <span class="new_userpost">
      <%= link_to t('.new_post'), new_user_userpost_path(current_user) %>
    </span>
  </a>
</div>

app/views/shared/_userpost_form.html.erb
<%= form_for @userpost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit t('.submit') %>
    <%= button_tag t('.cancel'),:type => 'button',:class => "subBtn",
                  :onclick => "location.href = '#{root_path}'" %>
  </div>
<% end %>